{{- $fullname := include "orchestrator.fullname" . }}
{{- $replicas := int .Values.replicas }}
{{- $raftNodes := include "orchestrator.raftlist" . | splitList "," }}
{{- $conf := .Values.orchestratorConf }}
{{- $_ := set $conf "ListenAddress" ":3000" }}
{{- $_ := set $conf "MySQLTopologyCredentialsConfigFile" "/etc/orchestrator/orc-topology.cnf" }}
{{- $_ := set $conf "BackendDB" "sqlite" }}
{{- $_ := set $conf "SQLite3DataFile" "/var/lib/orchestrator/orc.db" }}
{{- $_ := set $conf "RaftEnabled" true }}
{{- $_ := set $conf "RaftDataDir" "/var/lib/orchestrator" }}
{{- $_ := set $conf "RaftAdvertise" "{{ .Env.HOSTNAME }}-svc" }}
{{- $_ := set $conf "RaftBind" "{{ .Env.HOSTNAME }}" }}
{{- $_ := set $conf "HTTPAdvertise" "http://{{ .Env.HOSTNAME }}-svc:80" }}
{{- if eq 1 $replicas -}}
{{- $_ := set $conf "RaftNodes" (list) }}
{{- else -}}
{{- $_ := set $conf "RaftNodes" $raftNodes }}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orchestrator.fullname" . }}
  labels:
    app: {{ template "orchestrator.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  orchestrator.conf.json: {{ toPrettyJson $conf | quote }}
  orc-topology.cnf: |
    [client]
    user = {{ printf "{{ .Env.ORC_TOPOLOGY_USER }}" }}
    password = {{ printf "{{ .Env.ORC_TOPOLOGY_PASSWORD }}" }}
